from odoo import models, fields, api


class AccountMove(models.Model):
    _inherit = "account.move"

    umrah_customer_id = fields.Many2one("umrah.customer")
    umrah_contract_id = fields.Many2one("umrah.customer.contract")
    umrah_group_id = fields.Many2one("umrah.group")

    # Back-links to source records for invoices generated by this module.
    # Additive only — no posting logic is overridden here.
    umrah_visa_id = fields.Many2one("umrah.visa", string="Umrah Visa")
    umrah_transport_program_id = fields.Many2one(
        "umrah.transport.program", string="Transport Program"
    )