{
    'name': 'Era Saudi Law Firm Management',
    'summary': 'Cases, hearings, billing and client trust accounting for Saudi law firms',
    'version': '19.0.52.0.0',
    'category': 'Services',
    'author': 'Era Group',
    'email': 'info@era.net.sa',
    'website': 'https://era.net.sa',
    'assets': {
        'web.assets_backend': [
            'era_law_firm/static/src/scss/legal_dashboard.scss',
            'era_law_firm/static/src/scss/legal_ornament_art.scss',
            'era_law_firm/static/src/scss/legal_ornament.scss',
            'era_law_firm/static/src/scss/legal_home_tile.scss',
        ],
    },
    'license': 'LGPL-3',
    'depends': ['mail', 'portal', 'calendar', 'account', 'hr_timesheet', 'l10n_sa', 'l10n_sa_edi'],
    'data': [
        'security/legal_security.xml', 'security/legal_record_rules.xml', 'security/legal_portal_security.xml', 'security/ir.model.access.csv',
        'data/legal_product_data.xml',
        'data/legal_case_stage_data.xml', 'data/legal_deadline_rule_data.xml', 'data/legal_cron_data.xml',
        'data/legal_judiciary_data.xml',
        'data/legal_trust_setup_data.xml',
        'data/legal_judiciary_migration.xml',
        'views/legal_views.xml',
        'views/legal_conflict_views.xml',
        'views/legal_guide_views.xml',
        'data/legal_guide_data.xml',
        'views/legal_dashboard_views.xml',
        'wizard/legal_intake_views.xml',
        'views/legal_judiciary_views.xml',
        'views/legal_finance_views.xml',
        'views/legal_advanced_views.xml',
        'wizard/legal_wizard_views.xml',
        'wizard/legal_demo_views.xml',
        'views/account_move_views.xml',
        'views/res_config_settings_views.xml', 'views/legal_portal_templates.xml',
        'report/legal_reports.xml',
    ],
    'demo': ['data/legal_demo_data.xml'],
    'images': ['static/description/banner.png'],
    'application': True,
    'installable': True,
}
