from . import (
    seo_mixin,
    seo_schema_engine,  # pure-Python module, not a model
    seo_schema_instance,
    seo_schema_template,
    seo_redirect,
    seo_redirect_log,
    ir_http,
    seo_sitemap_config,
    seo_robots_rule,
    seo_audit_run,
    seo_audit_finding,
    seo_hreflang,
    website,
    website_page,
    website_menu,
    content_block,
    res_partner,
    res_config_settings,
    seo_status,
)
