# -*- coding: utf-8 -*-
from odoo import api, fields, models, _

# Traffic-light colours shared by the heatmap dots, the badges and the legend.
RISK_COLOR = {"high": "#38a169", "medium": "#d69e2e", "low": "#e05b49"}
RISK_LABEL = {"high": "High confidence", "medium": "Moderate",
              "low": "Low / risky"}
# Relative-risk (coefficient of variation) shown on the heatmap's Y axis is
# capped here so one near-break-even model can't flatten everything else.
CV_CAP = 1.5


class MonteCarloDashboard(models.TransientModel):
    """A read-only executive overview across every simulation model: portfolio
    KPIs, a risk heatmap (success confidence vs. relative uncertainty) and a
    table ranked riskiest-first. Built as server-rendered HTML/SVG (no JS), so
    it matches the rest of the module and prints in reports."""
    _name = "monte.carlo.dashboard"
    _description = "Monte Carlo Manager Dashboard"

    objective_filter = fields.Selection(
        selection=[
            ("all", "All objectives"),
            ("revenue_forecast", "Revenue Forecast"),
            ("cost_estimation", "Cost Estimation"),
            ("profit_analysis", "Profit Analysis"),
            ("project_duration", "Project Duration"),
            ("inventory_demand", "Inventory Demand"),
            ("custom", "Custom"),
        ],
        string="Objective", default="all", required=True,
        help="Limit the dashboard to one objective, or show them all.")
    board_html = fields.Html(
        string="Dashboard", compute="_compute_board", sanitize=False)

    @api.depends("objective_filter")
    def _compute_board(self):
        for rec in self:
            rec.board_html = rec._render_board()

    # ------------------------------------------------------------------
    # Data
    # ------------------------------------------------------------------
    def _dashboard_models(self):
        """Standalone models the user may see that have a completed run.

        Models auto-generated by the one-click "Simulate this" mixin (e.g. one
        per CRM opportunity, ``source_model`` set) are excluded: they are
        per-record forecasts, not portfolio models, and there can be very many
        of them. Archived models are excluded by the default active filter.
        """
        self.ensure_one()
        domain = [("source_model", "=", False)]
        if self.objective_filter and self.objective_filter != "all":
            domain.append(("objective", "=", self.objective_filter))
        models = self.env["monte.carlo.model"].search(domain)
        return models.filtered(lambda m: m.latest_risk != "none")

    @staticmethod
    def _fmt_money(model, value):
        currency = model.currency_id
        if currency:
            return currency.format(value or 0.0)
        return "{:,.0f}".format(value or 0.0)

    # ------------------------------------------------------------------
    # Rendering
    # ------------------------------------------------------------------
    def _render_board(self):
        self.ensure_one()
        models = self._dashboard_models()
        if not models:
            return ('<div class="text-muted" style="padding:24px;">%s</div>'
                    % _("No completed simulation runs yet. Run a model, then "
                        "reopen this dashboard to see the portfolio overview."))
        ranked = models.sorted(key=lambda m: m.latest_success)  # riskiest first
        return ('<div style="font-family:sans-serif;">%s%s%s</div>'
                % (self._render_kpis(models),
                   self._render_heatmap(models),
                   self._render_table(ranked)))

    def _render_kpis(self, models):
        n = len(models)
        high = len(models.filtered(lambda m: m.latest_risk == "high"))
        med = len(models.filtered(lambda m: m.latest_risk == "medium"))
        low = len(models.filtered(lambda m: m.latest_risk == "low"))
        avg = sum(models.mapped("latest_success")) / n if n else 0.0

        def box(label, value, color):
            return (
                '<div style="flex:1;min-width:150px;background:#fff;border:1px '
                'solid #e3e8ee;border-top:3px solid %s;border-radius:6px;'
                'padding:10px 14px;margin:4px;">'
                '<div style="font-size:22px;font-weight:700;color:%s;">%s</div>'
                '<div style="font-size:12px;color:#5b6b7b;">%s</div></div>'
                % (color, color, value, label))

        boxes = (
            box(_("Models with results"), n, "#14385f")
            + box(_("High confidence"), high, RISK_COLOR["high"])
            + box(_("Moderate"), med, RISK_COLOR["medium"])
            + box(_("Need attention"), low, RISK_COLOR["low"])
            + box(_("Avg. success confidence"), "%.0f%%" % avg, "#2b6cb0"))
        return ('<div style="display:flex;flex-wrap:wrap;margin-bottom:10px;">'
                '%s</div>' % boxes)

    def _render_heatmap(self, models):
        Run = self.env["monte.carlo.run"]
        esc = Run._svg_escape
        width, height = 1000.0, 480.0
        ml, mr, mt, mb = 120.0, 30.0, 28.0, 64.0
        plot_w, plot_h = width - ml - mr, height - mt - mb
        base_y = mt + plot_h

        def px(success):
            return ml + min(max(success, 0.0), 100.0) / 100.0 * plot_w

        def py(cv):
            return base_y - min(max(cv, 0.0), CV_CAP) / CV_CAP * plot_h

        parts = []
        # Quadrant shading: bottom-right = healthy (high confidence, low risk),
        # top-left = fragile (low confidence, high risk).
        parts.append('<rect x="%.1f" y="%.1f" width="%.1f" height="%.1f" '
                     'fill="#38a169" opacity="0.06"/>'
                     % (px(50), py(0.5), px(100) - px(50), base_y - py(0.5)))
        parts.append('<rect x="%.1f" y="%.1f" width="%.1f" height="%.1f" '
                     'fill="#e05b49" opacity="0.06"/>'
                     % (ml, mt, px(50) - ml, py(0.5) - mt))
        # Gridlines + X ticks (confidence) and Y ticks (relative risk).
        for s in (0, 25, 50, 75, 100):
            x = px(s)
            parts.append('<line x1="%.1f" y1="%.1f" x2="%.1f" y2="%.1f" '
                         'stroke="%s" stroke-width="1"/>'
                         % (x, mt, x, base_y, "#cbd5e0" if s == 50 else "#eef2f6"))
            parts.append('<text x="%.1f" y="%.1f" fill="#5b6b7b" font-size="11" '
                         'text-anchor="middle">%d%%</text>' % (x, base_y + 18, s))
        for cv in (0.0, 0.5, 1.0, CV_CAP):
            y = py(cv)
            parts.append('<line x1="%.1f" y1="%.1f" x2="%.1f" y2="%.1f" '
                         'stroke="%s" stroke-width="1"/>'
                         % (ml, y, ml + plot_w, y,
                            "#cbd5e0" if cv == 0.5 else "#eef2f6"))
            label = ("≥%.0f%%" % (CV_CAP * 100)) if cv == CV_CAP else "%.0f%%" % (cv * 100)
            parts.append('<text x="%.1f" y="%.1f" fill="#5b6b7b" font-size="11" '
                         'text-anchor="end">%s</text>' % (ml - 8, y + 4, label))
        # Axis titles.
        parts.append('<text x="%.1f" y="%.1f" fill="#3b4754" font-size="12" '
                     'text-anchor="middle">%s</text>'
                     % (ml + plot_w / 2.0, height - 12, _("Success confidence →")))
        parts.append('<text x="16" y="%.1f" fill="#3b4754" font-size="12" '
                     'text-anchor="middle" transform="rotate(-90 16 %.1f)">%s</text>'
                     % (mt + plot_h / 2.0, mt + plot_h / 2.0,
                        _("Relative uncertainty ↑")))
        # One dot per model, coloured by confidence; label to the side.
        for model in models:
            cx, cy = px(model.latest_success), py(model.latest_cv)
            color = RISK_COLOR.get(model.latest_risk, "#5b6b7b")
            parts.append('<circle cx="%.1f" cy="%.1f" r="6" fill="%s" '
                         'opacity="0.9" stroke="#fff" stroke-width="1.5"/>'
                         % (cx, cy, color))
            name = (model.name or "")[:22]
            anchor, dx = ("end", -9) if cx > ml + plot_w * 0.75 else ("start", 9)
            parts.append('<text x="%.1f" y="%.1f" fill="#3b4754" font-size="11" '
                         'text-anchor="%s">%s</text>'
                         % (cx + dx, cy + 4, anchor, esc(name)))
        svg = ('<svg viewBox="0 0 1000 480" preserveAspectRatio="xMidYMid meet" '
               'style="width:100%%;height:auto;max-width:980px;'
               'font-family:sans-serif;">%s</svg>' % "".join(parts))

        def chip(level):
            return ('<span style="margin-inline-end:14px;white-space:nowrap;">'
                    '<span style="display:inline-block;width:11px;height:11px;'
                    'background:%s;border-radius:50%%;vertical-align:middle;'
                    'margin-inline-end:4px;"></span>%s</span>'
                    % (RISK_COLOR[level], _(RISK_LABEL[level])))
        legend = (
            '<div style="margin:2px 0 12px;font-size:12px;color:#5b6b7b;">'
            + chip("high") + chip("medium") + chip("low")
            + '<span style="margin-inline-start:6px;">%s</span></div>'
            % _("Bottom-right (high confidence, low uncertainty) is the healthy "
                "zone; top-left needs attention."))
        return ('<div style="border:1px solid #e3e8ee;border-radius:6px;'
                'padding:10px;margin-bottom:12px;"><div style="font-weight:600;'
                'color:#14385f;margin-bottom:6px;">%s</div>%s%s</div>'
                % (_("Risk heatmap"), svg, legend))

    def _render_table(self, models):
        Run = self.env["monte.carlo.run"]
        esc = Run._svg_escape
        objective_sel = dict(
            self.env["monte.carlo.model"]._fields["objective"]
            ._description_selection(self.env))
        th = ('padding:6px 10px;border-bottom:2px solid #cbd5e0;'
              'text-align:start;font-weight:600;white-space:nowrap;')
        td = 'padding:6px 10px;border-bottom:1px solid #edf1f5;white-space:nowrap;'
        headers = [_("Model"), _("Objective"), _("Expected"),
                   _("Range (P5–P95)"), _("Success"), _("Confidence"),
                   _("Top driver")]
        head = "".join('<th style="%s%s">%s</th>'
                       % (th, "text-align:end;" if h in (_("Expected"), _("Success"))
                          else "", h) for h in headers)
        body = []
        for model in models:
            color = RISK_COLOR.get(model.latest_risk, "#5b6b7b")
            badge = ('<span style="background:%s;color:#fff;border-radius:10px;'
                     'padding:1px 9px;font-size:11px;">%s</span>'
                     % (color, _(RISK_LABEL.get(model.latest_risk, ""))))
            rng = "%s – %s" % (self._fmt_money(model, model.latest_p05),
                               self._fmt_money(model, model.latest_p95))
            cells = [
                '<td style="%s">%s</td>' % (td, esc(model.name or "")),
                '<td style="%scolor:#5b6b7b;">%s</td>'
                % (td, esc(objective_sel.get(model.objective, ""))),
                '<td style="%stext-align:end;font-variant-numeric:tabular-nums;">'
                '%s</td>' % (td, esc(self._fmt_money(model, model.latest_mean))),
                '<td style="%scolor:#5b6b7b;font-variant-numeric:tabular-nums;">'
                '%s</td>' % (td, esc(rng)),
                '<td style="%stext-align:end;font-weight:600;color:%s;">%.0f%%</td>'
                % (td, color, model.latest_success),
                '<td style="%s">%s</td>' % (td, badge),
                '<td style="%scolor:#5b6b7b;">%s</td>'
                % (td, esc(model.latest_driver or "—")),
            ]
            body.append("<tr>%s</tr>" % "".join(cells))
        return (
            '<div style="font-weight:600;color:#14385f;margin-bottom:6px;">%s</div>'
            '<table style="border-collapse:collapse;width:100%%;font-size:13px;">'
            '<thead><tr>%s</tr></thead><tbody>%s</tbody></table>'
            '<div style="margin-top:6px;font-size:12px;color:#8b97a3;">%s</div>'
            % (_("Models ranked riskiest-first"), head, "".join(body),
               _("Sorted by success confidence (lowest first) so the models "
                 "that need attention are on top.")))

    def action_refresh(self):
        """Force a recompute (the board reads live data each time it opens)."""
        return True
