# -*- coding: utf-8 -*-
import re

from odoo import api, fields, models, _
from odoo.exceptions import ValidationError

# Predefined formulas. Each entry lists the variable codes it expects and a
# vectorised callable receiving a dict of {code: numpy.ndarray}. Keeping the
# formulas predefined (instead of raw Python) is the safe default asked for in
# the spec; ``custom_python_limited`` adds an opt-in, sandboxed expression.
PREDEFINED_FORMULAS = {
    "simple_revenue": {
        "label": "Revenue = Leads x Conversion Rate x Average Deal Value",
        "required_codes": ["leads", "conversion_rate", "average_deal_value"],
    },
    "profit": {
        "label": "Profit = Units x (Unit Price - Unit Cost) - Fixed Cost",
        "required_codes": ["units", "unit_price", "unit_cost"],
        "optional_codes": ["fixed_cost"],
    },
}


class MonteCarloModel(models.Model):
    _name = "monte.carlo.model"
    _description = "Monte Carlo Simulation Model"
    _order = "name"

    name = fields.Char(
        string="Name", required=True,
        help="A short, recognisable name for this simulation model "
             "(e.g. Q3 Revenue Forecast).")
    description = fields.Text(
        string="Description",
        help="Free notes: the business question this model answers and any "
             "assumptions behind the inputs.")
    active = fields.Boolean(
        string="Active", default=True,
        help="Untick to archive this model and hide it from the default list "
             "without deleting it or its runs.")

    variable_ids = fields.One2many(
        "monte.carlo.variable", "model_id", string="Variables", copy=True,
        help="The uncertain inputs of this model. Each variable is sampled "
             "from its probability distribution on every iteration.")
    run_ids = fields.One2many(
        "monte.carlo.run", "model_id", string="Runs",
        help="Every execution of this model. Each run stores its own results "
             "and summary statistics.")
    correlation_ids = fields.One2many(
        "monte.carlo.correlation", "model_id", string="Input Correlations",
        help="Optional links between inputs that move together (e.g. price and "
             "demand). The engine reproduces them when sampling, without "
             "changing any single input's own distribution.")

    variable_count = fields.Integer(
        string="Variable Count", compute="_compute_counts",
        help="Number of input variables defined on this model.")
    run_count = fields.Integer(
        string="Run Count", compute="_compute_counts",
        help="Number of times this model has been run.")
    result_count = fields.Integer(
        string="Result Count", compute="_compute_counts",
        help="Total number of stored result rows across all runs of this model.")

    default_iterations = fields.Integer(
        string="Default Iterations", default=10000,
        help="Number of scenarios (random draws) generated by default for each "
             "run. More iterations give a smoother, more reliable distribution; "
             "10,000 is a good starting point.")

    result_storage = fields.Selection(
        selection=[
            ("full", "Every scenario"),
            ("sample", "Representative sample"),
            ("summary", "Summary only"),
        ],
        string="Result Storage", default="full", required=True,
        help="How many result rows to keep in the database. The summary "
             "statistics and the distribution / drivers charts are ALWAYS "
             "computed from every scenario, so they stay exact whatever you "
             "pick here — this only controls stored rows. 'Every scenario' "
             "keeps them all; 'Representative sample' keeps a random subset "
             "(lighter); 'Summary only' keeps none (lightest).")
    result_sample_size = fields.Integer(
        string="Sample Size", default=2000,
        help="Number of result rows to keep when Result Storage is "
             "'Representative sample'.")

    objective = fields.Selection(
        selection=[
            ("revenue_forecast", "Revenue Forecast"),
            ("cost_estimation", "Cost Estimation"),
            ("profit_analysis", "Profit Analysis"),
            ("project_duration", "Project Duration"),
            ("inventory_demand", "Inventory Demand"),
            ("custom", "Custom"),
        ],
        string="Objective", default="revenue_forecast", required=True,
        help="The business question this model answers. It does not change the "
             "simulated outcomes, but it orients the risk reporting: for Cost "
             "Estimation, Project Duration and Inventory Demand a LOWER outcome "
             "counts as success (the success probability uses 'below threshold' "
             "and VaR/CVaR measure the high tail); for the other objectives a "
             "HIGHER outcome is success. It also enables the negative-outcome "
             "data-quality warning for objectives that cannot be negative.")

    formula_type = fields.Selection(
        selection=[
            ("simple_revenue", "Simple Revenue"),
            ("profit", "Profit"),
            ("custom_python_limited", "Custom (Limited Expression)"),
        ],
        string="Formula", default="simple_revenue", required=True,
        help="How the output is computed from the variables. 'Simple Revenue' "
             "and 'Profit' are ready-made formulas with fixed variable codes; "
             "'Custom' lets you write your own arithmetic expression.")
    formula_expression = fields.Text(
        string="Custom Expression",
        help="Used only when Formula is 'Custom'. Write an arithmetic "
             "expression using the variable codes, e.g. "
             "leads * conversion_rate * average_deal_value. "
             "Allowed helpers: min, max, abs, where, exp, log, sqrt.")
    formula_help = fields.Char(
        string="Formula Help", compute="_compute_formula_help",
        help="Reminder of the formula applied by the selected Formula type.")

    ai_summary = fields.Html(
        string="AI Summary", compute="_compute_ai_summary", sanitize=False,
        help="The AI-generated summary of this model's most recent completed "
             "run, shown here for quick reference. Open a run and click "
             "'Explain with AI' to generate or refresh it.")
    ai_summary_preview = fields.Text(
        string="AI Summary Preview", compute="_compute_ai_summary")

    currency_id = fields.Many2one(
        "res.currency", string="Currency",
        default=lambda self: self.env.company.currency_id,
        help="Currency used to display the monetary results of this model.")
    company_id = fields.Many2one(
        "res.company", string="Company",
        default=lambda self: self.env.company,
        help="Company that owns this simulation model.")
    # Link back to the business record this model was generated from (via the
    # one-click "Simulate this" mixin), so re-simulating reuses the same model.
    source_model = fields.Char(string="Source Model", index=True, copy=False)
    source_res_id = fields.Integer(string="Source Record", index=True,
                                   copy=False)

    # Latest-run snapshot (for the manager dashboard and list overview) --------
    latest_run_id = fields.Many2one(
        "monte.carlo.run", string="Latest Run", compute="_compute_latest_run",
        help="The most recently completed run of this model.")
    latest_run_date = fields.Datetime(
        string="Last Run", compute="_compute_latest_run")
    latest_mean = fields.Float(
        string="Expected", compute="_compute_latest_run",
        help="Mean outcome of the latest completed run.")
    latest_p05 = fields.Float(string="Downside (P5)", compute="_compute_latest_run")
    latest_p95 = fields.Float(string="Upside (P95)", compute="_compute_latest_run")
    latest_std = fields.Float(string="Std. Dev.", compute="_compute_latest_run")
    latest_success = fields.Float(
        string="Success %", compute="_compute_latest_run",
        help="Objective-aware probability of reaching the success threshold in "
             "the latest run (chance of staying under it for cost/time goals).")
    latest_cv = fields.Float(
        string="Relative Risk", compute="_compute_latest_run",
        help="Coefficient of variation (std / |mean|) of the latest run — a "
             "scale-free measure of how uncertain the outcome is.")
    latest_risk = fields.Selection(
        selection=[("high", "High confidence"), ("medium", "Moderate"),
                   ("low", "Low / risky"), ("none", "No run yet")],
        string="Confidence", compute="_compute_latest_run",
        help="Traffic-light read of the latest run's success confidence: "
             "green ≥ 80%, amber ≥ 50%, red below.")
    latest_driver = fields.Char(
        string="Top Driver", compute="_compute_latest_run",
        help="The input that most drives the outcome in the latest run.")

    def _latest_done_runs(self, extra_domain=None, fields_to_fetch=None):
        """Return ``{model_id: newest done run}`` for the models in ``self``.

        One search_fetch limited to the listed columns: reading ``run_ids``
        and sorting in Python would prefetch every stored field (including the
        AI summary Html) of every historical run of every model in the batch.
        """
        domain = [("model_id", "in", self.ids), ("state", "=", "done")]
        if extra_domain:
            domain += extra_domain
        runs = self.env["monte.carlo.run"].search_fetch(
            domain, ["model_id", "finished_at", "create_date"]
            + list(fields_to_fetch or []),
            order="finished_at desc, create_date desc, id desc")
        latest = {}
        for run in runs:
            latest.setdefault(run.model_id.id, run)
        return latest

    @api.depends("objective", "run_ids.state", "run_ids.finished_at",
                 "run_ids.summary_mean", "run_ids.summary_std",
                 "run_ids.p05", "run_ids.p95",
                 "run_ids.probability_above_threshold",
                 "run_ids.probability_below_threshold",
                 "run_ids.sensitivity_data")
    def _compute_latest_run(self):
        latest_by_model = self._latest_done_runs(fields_to_fetch=[
            "summary_mean", "summary_std", "p05", "p95",
            "probability_above_threshold", "probability_below_threshold",
            "sensitivity_data"])
        for model in self:
            run = latest_by_model.get(model.id)
            if not run:
                model.latest_run_id = False
                model.latest_run_date = False
                model.latest_mean = model.latest_p05 = model.latest_p95 = 0.0
                model.latest_std = model.latest_success = model.latest_cv = 0.0
                model.latest_risk = "none"
                model.latest_driver = False
                continue
            prob = run._success_metric()[0]
            mean = run.summary_mean
            model.latest_run_id = run.id
            model.latest_run_date = run.finished_at
            model.latest_mean = mean
            model.latest_p05 = run.p05
            model.latest_p95 = run.p95
            model.latest_std = run.summary_std
            model.latest_success = prob
            model.latest_cv = (run.summary_std / abs(mean)
                               if abs(mean) > 1e-9 else (999.0 if run.summary_std else 0.0))
            model.latest_risk = ("high" if prob >= 80.0
                                 else "medium" if prob >= 50.0 else "low")
            drivers = (run.sensitivity_data or {}).get("drivers") or []
            model.latest_driver = drivers[0]["name"] if drivers else False

    @api.model
    def _mc_sync_from_recipe(self, source, recipe):
        """Create or refresh a simulation model (and its variables) for a
        ``source`` record from a recipe dict (see monte.carlo.simulable)."""
        Variable = self.env["monte.carlo.variable"]
        vals = {
            "name": recipe["name"],
            "objective": recipe.get("objective", "revenue_forecast"),
            "formula_type": recipe.get("formula_type", "simple_revenue"),
            "source_model": source._name,
            "source_res_id": source.id,
        }
        if recipe.get("company_id"):
            # Stamp the model with the SOURCE record's company (not the user's
            # active company) so runs/results land in the right company.
            vals["company_id"] = recipe["company_id"]
        if recipe.get("currency_id"):
            vals["currency_id"] = recipe["currency_id"]
        if recipe.get("formula_expression"):
            vals["formula_expression"] = recipe["formula_expression"]
        if recipe.get("result_storage"):
            vals["result_storage"] = recipe["result_storage"]
        model = self.search([("source_model", "=", source._name),
                             ("source_res_id", "=", source.id)], limit=1)
        if model:
            model.write(vals)
            # Drop correlations first (they reference the variables), then the
            # variables, so both are rebuilt cleanly from the recipe.
            model.correlation_ids.unlink()
            model.variable_ids.unlink()
        else:
            model = self.create(vals)
        code_to_id = {}
        for index, variable in enumerate(recipe.get("variables", [])):
            record = Variable.create(dict(variable, model_id=model.id,
                                          sequence=index * 10))
            code_to_id[record.code] = record.id
        # Optional correlations, expressed in the recipe by variable CODE so the
        # source model needn't know the freshly-created variable ids.
        for corr in recipe.get("correlations", []):
            v1 = code_to_id.get(corr.get("variable1_code"))
            v2 = code_to_id.get(corr.get("variable2_code"))
            if v1 and v2 and v1 != v2:
                self.env["monte.carlo.correlation"].create({
                    "model_id": model.id,
                    "variable1_id": v1, "variable2_id": v2,
                    "coefficient": corr.get("coefficient", 0.0),
                })
        return model

    def _mc_simulate_now(self, success_threshold=None):
        """Create a run for this model, execute it and return it."""
        self.ensure_one()
        vals = {"model_id": self.id}
        if success_threshold is not None:
            vals["success_threshold"] = success_threshold
        # One-click simulations are quick and don't need an AI summary.
        run = self.env["monte.carlo.run"].with_context(
            mc_skip_ai_summary=True).create(vals)
        run.action_run_simulation()
        return run

    @api.model
    def _cron_cleanup_crm_simulations(self):
        """Daily housekeeping for one-click CRM value simulations: force
        summary-only storage, keep only each opportunity's latest run (the
        forecast reads its summary stats), and drop the bulky per-iteration
        result rows entirely."""
        crm_models = self.search([("source_model", "=", "crm.lead")])
        if not crm_models:
            return
        stale = crm_models.filtered(lambda m: m.result_storage != "summary")
        if stale:
            stale.write({"result_storage": "summary"})
        leads = self.env["crm.lead"].browse(
            crm_models.mapped("source_res_id")).exists()
        # Drop models whose opportunity was deleted: they can never be reused
        # by _mc_sync_from_recipe and would pile up as dead 'Deal value — ...'
        # entries forever (cascade clears their variables/correlations/runs).
        alive_ids = set(leads.ids)
        dead = crm_models.filtered(lambda m: m.source_res_id not in alive_ids)
        if dead:
            dead.unlink()
            crm_models -= dead
        runs = self.env["monte.carlo.run"].search(
            [("model_id", "in", crm_models.ids)])
        keep = leads.mapped("mc_run_id")
        # Delete older runs (ondelete=cascade also clears their result rows)...
        (runs - keep).unlink()
        # ...and purge any result rows still attached to the kept latest runs.
        self.env["monte.carlo.result"].search(
            [("run_id", "in", keep.ids)]).unlink()

    @api.autovacuum
    def _gc_crm_simulations(self):
        """Run the CRM-simulation cleanup as part of the daily autovacuum too —
        this keeps working even on neutralized databases, where the dedicated
        cron is disabled."""
        self._cron_cleanup_crm_simulations()

    @api.depends("variable_ids", "run_ids", "run_ids.result_ids")
    def _compute_counts(self):
        # Aggregate result rows per run in a single read_group to avoid loading
        # potentially tens of thousands of result records into memory.
        result_data = self.env["monte.carlo.result"]._read_group(
            [("run_id.model_id", "in", self.ids)],
            groupby=["run_id"], aggregates=["__count"])
        per_run = {run.id: count for run, count in result_data}
        for record in self:
            record.variable_count = len(record.variable_ids)
            record.run_count = len(record.run_ids)
            record.result_count = sum(
                per_run.get(run.id, 0) for run in record.run_ids)

    @api.depends("formula_type")
    def _compute_formula_help(self):
        for record in self:
            formula = PREDEFINED_FORMULAS.get(record.formula_type)
            if formula:
                record.formula_help = formula["label"]
            else:
                record.formula_help = _(
                    "Custom expression evaluated over the variable codes.")

    @api.depends("run_ids.ai_interpretation", "run_ids.state",
                 "run_ids.finished_at")
    def _compute_ai_summary(self):
        """Mirror the AI summary of the most recent completed run."""
        latest_by_model = self._latest_done_runs(
            extra_domain=[("ai_interpretation", "!=", False)],
            fields_to_fetch=["ai_interpretation"])
        for record in self:
            run = latest_by_model.get(record.id)
            html = (self.env["monte.carlo.run"]._format_ai_html(
                run.ai_interpretation) if run else False)
            record.ai_summary = html
            record.ai_summary_preview = self._html_to_multiline(html)

    @staticmethod
    def _html_to_multiline(html, limit=600):
        """Turn the AI summary HTML into bulleted, multi-line plain text so it
        wraps nicely as a list column."""
        if not html:
            return False
        text = re.sub(r"(?i)<li[^>]*>", "• ", html)
        text = re.sub(r"(?i)</li>|</p>|<br\s*/?>", "\n", text)
        text = re.sub(r"<[^>]+>", "", text)
        text = re.sub(r"[ \t]+", " ", text)
        lines = [line.strip() for line in text.split("\n")]
        text = "\n".join(line for line in lines if line).strip()
        if len(text) > limit:
            text = text[:limit].rstrip() + "…"
        return text or False

    @api.constrains("default_iterations")
    def _check_default_iterations(self):
        for record in self:
            if record.default_iterations < 1:
                raise ValidationError(
                    _("Default iterations must be at least 1."))

    @api.constrains("formula_type", "formula_expression")
    def _check_custom_expression(self):
        for record in self:
            if (record.formula_type == "custom_python_limited"
                    and not (record.formula_expression or "").strip()):
                raise ValidationError(_(
                    "A custom formula requires an expression."))

    def action_new_run(self):
        """Create a draft run for this model and open it."""
        self.ensure_one()
        run = self.env["monte.carlo.run"].create({"model_id": self.id})
        return {
            "type": "ir.actions.act_window",
            "name": _("Simulation Run"),
            "res_model": "monte.carlo.run",
            "view_mode": "form",
            "res_id": run.id,
            "target": "current",
        }

    def action_view_runs(self):
        self.ensure_one()
        return {
            "type": "ir.actions.act_window",
            "name": _("Simulation Runs"),
            "res_model": "monte.carlo.run",
            "view_mode": "list,form",
            "domain": [("model_id", "=", self.id)],
            "context": {"default_model_id": self.id},
        }

    def action_view_results(self):
        self.ensure_one()
        return {
            "type": "ir.actions.act_window",
            "name": _("Results - %s", self.name),
            "res_model": "monte.carlo.result",
            "view_mode": "list,graph,pivot",
            "domain": [("model_id", "=", self.id)],
        }

    def copy(self, default=None):
        """Duplicate the variables (copy=True on the One2many) AND the input
        correlations, remapping each correlation onto the freshly copied
        variables by code — a plain copy would point at the source model's
        variables and fail the same-model constraint."""
        new_models = super().copy(default)
        for old, new in zip(self, new_models):
            code_to_id = {v.code: v.id for v in new.variable_ids}
            for corr in old.correlation_ids:
                v1 = code_to_id.get(corr.variable1_id.code)
                v2 = code_to_id.get(corr.variable2_id.code)
                if v1 and v2 and v1 != v2:
                    corr.copy({"model_id": new.id,
                               "variable1_id": v1, "variable2_id": v2})
        return new_models
