#!/usr/bin/env python3
"""Draw the module's corner lattice, and write it where the stylesheet reads it.

Run from the module root:  python3 tools/make_ornament.py

Four files come out, from this one source, so they cannot drift apart:

  static/src/img/era_ornament.svg          for a human to open and look at
  static/src/img/era_ornament_rtl.svg      the same, mirrored
  static/src/scss/legal_ornament_art.scss  both drawings as data URIs

The stylesheet uses the third. A static file served from a fixed path carries
Cache-Control: max-age=604800, so a browser holds the old drawing for a week
after the art changes — which is exactly what happened the first time this was
redrawn. Inside the stylesheet it rides the asset bundle, whose URL Odoo hashes
from its contents, so a change invalidates itself.

About the drawing: a mashrabiya. What makes a pierced screen read as carved
wood is that its openings share edges — the eight-pointed star, the diamond
that opens between four stars, and the bars that tie one star to the next are
one continuous net. Drawn as separate stars it reads as stickers on a page,
which is what the first attempt at this looked like.

It is a corner, not a band, so it has a direction: the lattice is dense at the
corner it grows from and dissolves along the diagonal. That is why there are
two drawings — in an Arabic interface the corner is on the right, and a
mirrored copy is more honest than a stretched one.

The palette is the module's own green, grey and gold. Nothing here shares a
silhouette with any official mark: what is borrowed is a technique any
craftsman has, and the colours.
"""
import math
import pathlib
from urllib.parse import quote

W, H, STEP = 360, 180, 44
GREEN, GREY, GOLD = '#1B8354', '#8A9490', '#E2C260'
STAR_OUTER, STAR_INNER = 17.0, 7.2

HEADER = """<!-- Era law firm: a mashrabiya lattice for the corner of a screen.

     Generated by tools/make_ornament.py — edit that, not this.

     Eight-pointed stars tied to their neighbours by bars, with a diamond
     opening between each four: one net rather than a scatter of stars. It
     thins along the diagonal so the corner dissolves into the page instead of
     stopping at a line. Green, grey and gold — the module's palette, and the
     only thing it has in common with any official mark.
-->
"""


def star(cx, cy, outer, inner, points=8, rotate=0.0):
    """The eight-pointed opening a mashrabiya is cut around."""
    coords = []
    for index in range(points * 2):
        angle = rotate + index * math.pi / points
        radius = outer if index % 2 == 0 else inner
        coords.append(f'{cx + radius * math.cos(angle):.1f},{cy + radius * math.sin(angle):.1f}')
    return 'M' + 'L'.join(coords) + 'Z'


def diamond(cx, cy, radius):
    coords = [f'{cx + radius * math.cos(i * math.pi / 2):.1f},'
              f'{cy + radius * math.sin(i * math.pi / 2):.1f}' for i in range(4)]
    return 'M' + 'L'.join(coords) + 'Z'


def lattice():
    """The net itself, anchored at the top-left corner."""
    parts = []
    for row in range(5):
        for col in range(10):
            cx, cy = col * STEP + 6, row * STEP + 4
            # Distance from the corner along both axes at once: the lattice is
            # densest where it starts and gone by the far diagonal.
            reach = cx / W + cy / H
            if reach > 1.25:
                continue
            opacity = 0.5 - reach * 0.3
            if opacity <= 0.02:
                continue
            colour = (GREEN, GREY, GOLD)[(row + col) % 3]
            parts.append(
                f'  <path d="{star(cx, cy, STAR_OUTER, STAR_INNER, rotate=math.pi / 8)}" '
                f"fill='none' stroke='{colour}' stroke-width='1.15' opacity='{opacity:.2f}'/>")
            parts.append(
                f'  <path d="{diamond(cx + STEP / 2, cy + STEP / 2, 8.5)}" '
                f"fill='none' stroke='{colour}' stroke-width='1' opacity='{opacity * 0.8:.2f}'/>")
            parts.append(
                f'  <path d="M{cx + STAR_OUTER} {cy} L{cx + STEP - STAR_OUTER} {cy}" '
                f"stroke='{colour}' stroke-width='1' opacity='{opacity * 0.7:.2f}'/>")
            parts.append(
                f'  <path d="M{cx} {cy + STAR_OUTER} L{cx} {cy + STEP - STAR_OUTER}" '
                f"stroke='{colour}' stroke-width='1' opacity='{opacity * 0.7:.2f}'/>")
    return '\n'.join(parts).replace('"', "'")


def build(header, mirror=False):
    """One drawing. Mirrored, the fade has to turn with it."""
    x1, x2 = ('1', '0') if mirror else ('0', '1')
    open_group = (f"<g transform='translate({W},0) scale(-1,1)'>" if mirror else '<g>')
    return (
        f"{header}<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 {W} {H}' "
        f"width='{W}' height='{H}'>\n"
        '<defs>\n'
        f"  <linearGradient id='eraFade' x1='{x1}' y1='0' x2='{x2}' y2='1'>\n"
        "    <stop offset='0' stop-color='#fff' stop-opacity='1'/>\n"
        "    <stop offset='0.55' stop-color='#fff' stop-opacity='0.45'/>\n"
        "    <stop offset='1' stop-color='#fff' stop-opacity='0'/>\n"
        '  </linearGradient>\n'
        f"  <mask id='eraCorner'><rect width='{W}' height='{H}' fill='url(#eraFade)'/></mask>\n"
        '</defs>\n'
        "<g mask='url(#eraCorner)'>\n"
        f'{open_group}\n'
        f'{lattice()}\n'
        '</g>\n'
        '</g>\n'
        '</svg>\n')


def as_data_uri(drawing):
    """The stylesheet copy: url-encoded rather than base64, so it stays

    readable in the bundle and encodes smaller. Two characters decide whether
    it works at all — '#' would start a fragment and cut the drawing off at its
    first colour, and a double quote would close the CSS string — so every
    attribute above is single-quoted and '#' is left out of the safe set.
    """
    return quote(drawing, safe="=:/'<>?,.-_ ")


def main():
    root = pathlib.Path(__file__).resolve().parent.parent

    for mirror, name in ((False, 'era_ornament'), (True, 'era_ornament_rtl')):
        (root / f'static/src/img/{name}.svg').write_text(build(HEADER, mirror), encoding='utf-8')

    ltr, rtl = as_data_uri(build('')), as_data_uri(build('', mirror=True))
    scss = (
        '// Generated by tools/make_ornament.py — do not edit by hand.\n'
        '//\n'
        '// The drawing lives in the stylesheet rather than at a static URL so\n'
        "// that changing it invalidates itself: Odoo hashes a bundle's URL from\n"
        '// its contents, while /module/static/... is served with a week of\n'
        '// max-age and no version in the path.\n'
        '//\n'
        '// Two copies: the lattice grows out of one corner, and in an Arabic\n'
        '// interface that corner is the other one.\n'
        ':root {\n'
        f'  --era-ornament: url("data:image/svg+xml,{ltr}");\n'
        f'  --era-ornament-rtl: url("data:image/svg+xml,{rtl}");\n'
        '}\n')
    (root / 'static/src/scss/legal_ornament_art.scss').write_text(scss, encoding='utf-8')

    print(f'svg  {len(build(HEADER)) // 1024} KB each')
    print(f'scss {len(scss) // 1024} KB')


if __name__ == '__main__':
    main()
