#!/usr/bin/env python3
"""Draw the module's halftone band, and write it where the stylesheet reads it.

Run from the module root:  python3 tools/make_ornament.py

Two files come out, from this one source, so they cannot drift apart:

  static/src/img/era_ornament.svg          for a human to open and look at
  static/src/scss/legal_ornament_art.scss  the same drawing as a data URI

The stylesheet uses the second. A static file served from a fixed path carries
Cache-Control: max-age=604800, so a browser holds the old drawing for a week
after the art changes — which is exactly what happened the first time this was
redrawn. Inside the stylesheet it rides the asset bundle, whose URL Odoo hashes
from its contents, so a change invalidates itself.

About the drawing: the technique is the generic one — a regular grid where each
dot's size and opacity vary. The modulation is periodic waves along the WIDTH
plus per-dot noise; a wave that also runs down the height is a diagonal, and
diagonals in a dot field collect into shapes the eye names (this drew a tick,
once). The colours run green, grey, gold, green from edge to edge, with the
boundaries dithered so no line appears where one gives way to the next.
"""
import math
import pathlib
from urllib.parse import quote

W, H, STEP = 1440, 180, 36
GREEN, GREY, GOLD = '#1B8354', '#8A9490', '#E2C260'
SEQUENCE = [GREEN, GREY, GOLD, GREEN]
GROUP_OPACITY = '0.1'
TAU = math.tau

HEADER = """<!-- Era law firm: an original halftone band in the house palette.

     Generated by tools/make_ornament.py — edit that, not this.

     A regular grid where each dot's size and opacity vary, driven mostly by
     per-dot noise, so the field reads as texture and resolves into no figure.
     The shaping waves run along the width only: a wave that also ran down the
     height would draw diagonals, and diagonals in a dot field collect into
     shapes. The colours run green, grey, gold, green from edge to edge, with
     the boundaries dithered so no line appears between them. -->"""


def noise(x, y):
    """Deterministic per-dot value in 0..1, so every build is the same file."""
    return (math.sin(x * 12.9898 + y * 78.233) * 43758.5453) % 1.0


def band(x, cycles, phase=0.0):
    return math.sin(TAU * cycles * x / W + phase)


def colour_at(x, jitter):
    t = x / W * len(SEQUENCE)
    index = int(t)
    edge = t - index
    if edge > 0.88 and jitter > 0.5:
        index += 1
    elif edge < 0.12 and jitter > 0.5:
        index -= 1
    return SEQUENCE[max(0, min(len(SEQUENCE) - 1, index))]


def dots():
    for row in range(H // STEP + 1):
        for col in range(W // STEP + 1):
            x = col * STEP + (STEP / 2 if row % 2 else 0)
            y = row * STEP
            if x > W:
                continue
            n = noise(x, y)
            field = 0.30 * band(x, 3) + 0.18 * band(x, 8, 1.3) + 0.52 * (2 * n - 1)
            size = 0.5 + 0.5 * field
            # radius as a share of the width matches the house artwork's ~1.1%,
            # which is what lets it read at 10% opacity without raising it
            radius = (3.7 + 9.5 * size) * (1 - 0.4 * y / H)
            if radius < 1.5:
                continue
            opacity = round(min(1.0, max(0.22, 0.35 + 0.6 * size)), 2)
            yield (round(x, 1), round(y, 1), round(radius, 1),
                   opacity, colour_at(x, noise(y, x)))


def build(comment):
    circles = '\n'.join(
        f'<circle cx="{x}" cy="{y}" r="{r}" fill="{c}" opacity="{o}"/>'
        for x, y, r, o, c in dots())
    open_tag = (f'<svg width="{W}" height="{H}" viewBox="0 0 {W} {H}" fill="none" '
                'xmlns="http://www.w3.org/2000/svg">')
    head = f'{open_tag}\n{comment}\n' if comment else open_tag
    return f'''{head}<defs>
<linearGradient id="eraFade" x1="0" y1="0" x2="0" y2="{H}" gradientUnits="userSpaceOnUse">
<stop offset="0" stop-color="#fff" stop-opacity="1"/>
<stop offset=".5" stop-color="#fff" stop-opacity=".5"/>
<stop offset="1" stop-color="#fff" stop-opacity="0"/>
</linearGradient>
<mask id="eraFadeMask" maskUnits="userSpaceOnUse" x="0" y="0" width="{W}" height="{H}">
<rect width="{W}" height="{H}" fill="url(#eraFade)"/>
</mask>
</defs>
<g opacity="{GROUP_OPACITY}" mask="url(#eraFadeMask)">
{circles}
</g>
</svg>
'''


def main():
    root = pathlib.Path(__file__).resolve().parent.parent

    readable = build(HEADER)
    (root / 'static/src/img/era_ornament.svg').write_text(readable, encoding='utf-8')

    # The stylesheet copy is url-encoded rather than base64: it stays readable
    # in the bundle and encodes smaller. Two characters decide whether it works
    # at all — '#' would start a fragment and cut the drawing off at its first
    # colour, and a double quote would close the CSS string — so the attributes
    # are single-quoted here and '#' is left out of the safe set.
    inline = quote(build('').replace('"', "'"), safe="=:/'<>?,.-_ ")
    scss = (
        '// Generated by tools/make_ornament.py — do not edit by hand.\n'
        '//\n'
        '// The drawing lives in the stylesheet rather than at a static URL so\n'
        "// that changing it invalidates itself: Odoo hashes a bundle's URL from\n"
        '// its contents, while /module/static/... is served with a week of\n'
        '// max-age and no version in the path.\n'
        ':root {\n'
        f'  --era-ornament: url("data:image/svg+xml,{inline}");\n'
        '}\n')
    (root / 'static/src/scss/legal_ornament_art.scss').write_text(scss, encoding='utf-8')

    print(f'svg  {len(readable) // 1024} KB')
    print(f'scss {len(scss) // 1024} KB')


if __name__ == '__main__':
    main()
