{
    'name': 'Era Sales Commissions',
    'version': '19.0.2.0.0',
    'category': 'Sales',
    'summary': 'Unified sales representative commissions: commission on sales, '
               'on collection and quantity commission, agent rates, unit price '
               'tiers, central targets, settlements, accounting and optional '
               'payroll integration',
    'author': 'Era Group',
    'email': 'info@era.net.sa',
    'website': 'https://era.net.sa',
    'license': 'LGPL-3',
    'depends': [
        'sale',
        'account',
        'hr',
        'hr_payroll',
        'era_report_designs',
    ],
    'data': [
        'security/commission_security.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence_data.xml',
        'data/ir_cron_data.xml',
        'data/hr_payroll_data.xml',
        'report/commission_report_actions.xml',
        'report/commission_statement.xml',
        'views/commission_agent_views.xml',
        'views/commission_agent_rate_views.xml',
        'views/commission_unit_price_tier_views.xml',
        'views/commission_plan_views.xml',
        'views/commission_line_views.xml',
        'views/commission_target_views.xml',
        'views/commission_settlement_views.xml',
        'views/sale_order_views.xml',
        'views/account_move_views.xml',
        'views/account_payment_views.xml',
        'views/product_template_views.xml',
        'views/res_partner_views.xml',
        'views/res_config_settings_views.xml',
        'wizard/commission_generate_views.xml',
        'wizard/commission_simulate_views.xml',
        'views/commission_menus.xml',
    ],
    'application': False,
    'installable': True,
}
