{
    'name': 'Era Law Firm AI Governance',
    'summary': 'Governed AI drafting, review and case summaries for Saudi law firms',
    'version': '19.0.49.0.0',
    'category': 'Services',
    'author': 'Era Group',
    'email': 'info@era.net.sa',
    'website': 'https://era.net.sa',
    'license': 'LGPL-3',
    'depends': ['era_law_firm', 'ai', 'ai_app'],
    'post_init_hook': '_schedule_first_corpus_sync',
    'data': [
        'security/legal_ai_security.xml',
        'security/ir.model.access.csv',
        'data/legal_ai_agents_data.xml',
        'data/legal_ai_fields_data.xml',
        'data/legal_charter_data.xml',
        'data/moj_corpus_params.xml',
        'data/moj_corpus_cron.xml',
        'data/moj_agent_target.xml',
        'data/legal_ai_research_button_data.xml',
        'data/legal_ai_record_button_data.xml',
        'data/legal_ai_corpus_chat_data.xml',
        'data/legal_ai_playbooks_data.xml',
        'views/legal_ai_views.xml',
        'views/moj_corpus_views.xml',
        'views/legal_research_entry.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'era_law_firm_ai/static/src/js/era_app_watch.js',
            'era_law_firm_ai/static/src/js/era_ai_button_agent.js',
            'era_law_firm_ai/static/src/js/era_ai_button_agent.xml',
            'era_law_firm_ai/static/src/js/era_legal_research_action.js',
            'era_law_firm_ai/static/src/js/era_citation_dialog.js',
            'era_law_firm_ai/static/src/js/era_citation_dialog.xml',
        ],
    },
    'images': ['static/description/banner.png'],
    'installable': True,
    'auto_install': False,
    'application': False,
}
