{
    'name': 'Era Law Firm AI Governance',
    'summary': 'Governed AI drafting, review and case summaries for Saudi law firms',
    'version': '19.0.27.0.0',
    'category': 'Services',
    'author': 'Era Group',
    'email': 'info@era.net.sa',
    'website': 'https://era.net.sa',
    'license': 'LGPL-3',
    'depends': ['era_law_firm', 'ai', 'ai_app'],
    'data': [
        'security/legal_ai_security.xml',
        'security/ir.model.access.csv',
        'data/legal_ai_agents_data.xml',
        'data/legal_ai_fields_data.xml',
        'data/legal_charter_data.xml',
        'data/moj_corpus_params.xml',
        'data/moj_corpus_cron.xml',
        'data/moj_agent_target.xml',
        'views/legal_ai_views.xml',
        'views/moj_corpus_views.xml',
    ],
    'images': ['static/description/banner.png'],
    'installable': True,
    'auto_install': False,
    'application': False,
}
