from . import legal_core
from . import legal_finance
from . import res_config
from . import account_move
from . import advanced
from . import legal_actions
from . import legal_trust_setup
from . import legal_judiciary
from . import legal_deletion
from . import legal_demo
from . import legal_help
from . import legal_defaults
from . import legal_next_step
