# -*- coding: utf-8 -*-
from . import cs_stage
from . import cs_next_action_log
from . import cs_account
from . import cs_service
from . import csm_offering
from . import csm_kpi_snapshot
from . import res_partner
from . import res_company
from . import res_config_settings
from . import crm_lead
from . import helpdesk_ticket
from . import voip_call
from . import survey_user_input
from . import ir_attachment
from . import cs_weekly_suggestion
from . import cs_success_profile
from . import cs_support_wallet
from . import cs_value_review
from . import cs_adoption_assessment
from . import cs_voc_insight
from . import account_return
from . import self_service_help
from . import cs_user_guide
from . import google_sheet_sync
from . import cs_ai_customer_share
