# -*- coding: utf-8 -*-
from odoo import fields, models


class CrmLead(models.Model):
    _inherit = 'crm.lead'

    cs_is_upsell = fields.Boolean(
        string='Customer Success Upsell', index=True,
        help="Marks an opportunity generated by the Customer Success team "
             "(expansion / cross-sell / renewal).")
    cs_upsell_type = fields.Selection([
        ('expansion', 'Expansion'),
        ('cross_sell', 'Cross-sell'),
        ('renewal', 'Renewal'),
    ], string='Upsell Type')
