# -*- coding: utf-8 -*-
from odoo import fields, models


class CsNextAction(models.Model):
    _name = 'cs.next.action'
    _description = 'Customer Success Next Best Action (AI)'
    _order = 'generated_on desc, id desc'
    _rec_name = 'name'
    _check_company_auto = True

    cs_account_id = fields.Many2one(
        'cs.account', string='Account', required=True, ondelete='cascade', index=True,
        check_company=True)
    partner_id = fields.Many2one(related='cs_account_id.partner_id', store=True, string='Customer')
    csm_user_id = fields.Many2one(related='cs_account_id.csm_user_id', store=True, string='CSM Engineer')
    company_id = fields.Many2one(related='cs_account_id.company_id', store=True, index=True)
    name = fields.Char(string='Recommended Action', required=True)
    reason = fields.Text(string='Reason')
    priority = fields.Selection([
        ('low', 'Low'),
        ('medium', 'Medium'),
        ('high', 'High'),
        ('urgent', 'Urgent'),
    ], default='medium', string='Priority')
    suggested_date = fields.Date(string='Suggested Date')
    generated_on = fields.Datetime(string='Generated On', default=fields.Datetime.now)
    generated_by = fields.Many2one(
        'res.users', string='Generated By', default=lambda self: self.env.user)
    state = fields.Selection([
        ('suggested', 'Suggested'),
        ('done', 'Done'),
        ('dismissed', 'Dismissed'),
    ], default='suggested', string='Status')
